{"meaning": "Finally block always gets executed either exception is generated or not", "syntax": "try:\n <body>\n raise Exception()\nexcept Exception as e:\n <exception handling>\nfinally:\n <clean-up>\n", "example": "def divide(x, y):\n    try:\n        result = x // y\n        print(\"Yeah ! Your answer is :\", result)\n    except ZeroDivisionError:\n        print(\"Sorry ! You are dividing by zero \")\n\ndivide(3, 2)\ndivide(3, 0)"}